import sys
from gooey import Gooey,GooeyParser

from write_mod import write_mod
from pathlib import Path
from helpers import root_path, get_nested_zip, extract_zip, read_json, write_json

# Handle Splash Screen
if getattr(sys, 'frozen', False):
    import pyi_splash
    pyi_splash.close()

@Gooey(program_name='KH1 Randomizer Mod Generator',
    image_dir=str(root_path().joinpath("Images")),
    header_bg_color="#554e3b")

def main():
    presets = read_json(root_path().joinpath("mod_generator_presets.json"))
    
    parser = GooeyParser()
    parser.add_argument("ap_zip_file",
        widget = "FileChooser",
        default = str(presets["ap_zip_file"]),
        metavar = "AP Zip File Output",
        help = "The zip file generated by Archipelago or the Seed Generator.")
    parser.add_argument("kh1_data_path",
        widget = "DirChooser",
        default = str(presets["kh1_data_path"]),
        metavar = "KH1 Data Path",
        help = "The path to your KH1 data extracted by OpenKH.")

    args = parser.parse_args()
    
    ap_zip_file = getattr(args, "ap_zip_file")
    if ap_zip_file is None or not Path(ap_zip_file).is_file() or Path(ap_zip_file).suffix.lower() != '.zip' or not Path(ap_zip_file).exists():
        FileNotFoundError(f"Error: {ap_zip_file} is not a valid zip file, or does not exist.")
   
    kh1_data_path = getattr(args, "kh1_data_path")
    if kh1_data_path is None or not Path(kh1_data_path).is_directory() or not Path(kh1_data_path).exists():
        FileNotFoundError(f"Error: {kh1_data_path} is not a valid directory, or does not exist.")
    
    write_json(root_path().joinpath("mod_generator_presets.json"), {
        "ap_zip_file": str(ap_zip_file),
        "kh1_data_path": str(kh1_data_path)
    })

    nested_zip: Path = get_nested_zip(ap_zip_file)
    if nested_zip:
        print("Not the seed zip, likely the main zip.")
        print("Assuming the seed only contains one player, lets try to find the inner zip.")
        extract_zip(ap_zip_file)
        print(f"Inner zip calculated as {nested_zip}")
    
    write_mod(nested_zip if nested_zip is not None else ap_zip_file, kh1_data_path)

if __name__ == "__main__":
    main()
