import sys
from gooey import Gooey,GooeyParser
import wx
import threading

from write_mod import write_mod
from pathlib import Path

from helpers import root_path, get_nested_zip, extract_zip, customize_gooey_window_async, customize_gooey_window
from config import read_presets, write_presets, get_theme_color

# Handle Splash Screen
if getattr(sys, 'frozen', False):
    import pyi_splash
    pyi_splash.close()

@Gooey(program_name='KH1 Randomizer Mod Generator',
    image_dir=str(root_path().joinpath("Images")),
    header_bg_color=get_theme_color("gooey","header_bg_color"),
    body_bg_color=get_theme_color("gooey","body_bg_color"),
    footer_bg_color=get_theme_color("gooey","footer_bg_color"),
    terminal_bg_color=get_theme_color("gooey","terminal_bg_color"),
    terminal_font_color=get_theme_color("gooey","terminal_font_color"))

def main():
    presets = read_presets("mod")
    
    parser = GooeyParser()
    parser.add_argument("ap_zip_file",
        widget = "FileChooser",
        default = str(presets["ap_zip_file"]),
        metavar = "AP Zip File Output",
        help = "The zip file generated by Archipelago.")
    parser.add_argument("kh1_data_path",
        widget = "DirChooser",
        default = str(presets["kh1_data_path"]),
        metavar = "KH1 Data Path",
        help = "The path to your KH1 data extracted by OpenKH.")
    
    customize_thread = threading.Thread(target=customize_gooey_window_async, args=(30.0, customize_gooey_window, get_theme_color), daemon=True)
    customize_thread.start()
    args = parser.parse_args()
        
    ap_zip_file = getattr(args, "ap_zip_file")
    if ap_zip_file is None or not Path(ap_zip_file).is_file() or Path(ap_zip_file).suffix.lower() != '.zip' or not Path(ap_zip_file).exists():
        FileNotFoundError(f"Error: {ap_zip_file} is not a valid zip file, or does not exist.")
   
    kh1_data_path = getattr(args, "kh1_data_path")
    if kh1_data_path is None or not Path(kh1_data_path).is_dir() or not Path(kh1_data_path).exists():
        FileNotFoundError(f"Error: {kh1_data_path} is not a valid directory, or does not exist.")
    
    write_presets("mod", args)

    nested_zip: Path = get_nested_zip(ap_zip_file)
    if nested_zip:
        print("Not the seed zip, likely the main zip.")
        print("Assuming the seed only contains one player, lets try to find the inner zip.")
        extract_zip(ap_zip_file)
        print(f"Inner zip calculated as {nested_zip}")
    
    write_mod(nested_zip if nested_zip is not None else ap_zip_file, kh1_data_path)

if __name__ == "__main__":
    main()
